// <auto-generated />
using System.Collections.Generic;
using LanguageLearningAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LanguageLearningAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260617053006_SeedItalianBeginnerVocab")]
    partial class SeedItalianBeginnerVocab
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LanguageLearningAPI.Models.LearningPlan", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanID"));

                    b.Property<List<int>>("GroupIDs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("PlanID");

                    b.HasIndex("UserID");

                    b.ToTable("LearningPlan", (string)null);
                });

            modelBuilder.Entity("LanguageLearningAPI.Models.TranslationGroup", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("GroupID");

                    b.ToTable("TranslationGroups", (string)null);
                });

            modelBuilder.Entity("LanguageLearningAPI.Models.TranslationPair", b =>
                {
                    b.Property<int>("PairID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PairID"));

                    b.Property<int>("GroupID")
                        .HasColumnType("integer");

                    b.Property<string>("SourceContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PairID");

                    b.HasIndex("GroupID");

                    b.ToTable("TranslationPairs", (string)null);
                });

            modelBuilder.Entity("LanguageLearningAPI.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("UserID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LanguageLearningAPI.Models.LearningPlan", b =>
                {
                    b.HasOne("LanguageLearningAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearningAPI.Models.TranslationPair", b =>
                {
                    b.HasOne("LanguageLearningAPI.Models.TranslationGroup", "TranslationGroup")
                        .WithMany("TranslationPairs")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TranslationGroup");
                });

            modelBuilder.Entity("LanguageLearningAPI.Models.TranslationGroup", b =>
                {
                    b.Navigation("TranslationPairs");
                });
#pragma warning restore 612, 618
        }
    }
}
